//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CnF.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public int Id { get; set; }
        public string BillNo { get; set; }
        public System.DateTime Date { get; set; }
        public int JobId { get; set; }
        public int AccountId { get; set; }
        public int TypeId { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
