//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CnF.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.Billings = new HashSet<Billing>();
            this.JobExpenses = new HashSet<JobExpens>();
        }
    
        public int Id { get; set; }
        public int JobType { get; set; }
        public string JobNo { get; set; }
        public System.DateTime JobDate { get; set; }
        public decimal Value { get; set; }
        public int ValueUnit { get; set; }
        public Nullable<int> ImporterId { get; set; }
        public Nullable<int> PortId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string LCNo { get; set; }
        public Nullable<System.DateTime> LCDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billing> Billings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobExpens> JobExpenses { get; set; }
    }
}
