//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CnF.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingLine
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> AgentType { get; set; }
        public int BranchId { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo { get; set; }
        public string FAX { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime MidifiedDate { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
